### ISSUE TITLE
Modelagem - Especificação Suplementar

### ISSUE THREAD

**Issue by nicaloribeiro** [Requisitos-de-Software/2020.1-Correios#10]
## Descrição
* É uma descrição mais elaborada de requisitos não funcionais encontrados ao longo da elaboração da documentação de análise de requisitos do aplicativo dos Correios;
* Entre os requisitos estão incluídos:
  * Requisitos legais e de regulamentação e padrões de aplicativo;
  * Atributos de qualidade do sistema a ser criado, incluindo requisitos de usabilidade, confiabilidade, desempenho e suportabilidade;
  * Outros requisitos, como aqueles para os sistemas e ambientes operacionais, compatibilidade com outro software e restrições de design;

## Tasks
- [x] Analisar os Requisitos não funcionais do aplicativo dos Correios;
- [x] Buscar novos requisitos não funcionais no aplicativo ( se necessário );
- [x] Buscar informações complementares no próprio portal dos Correios;
- [x] Elaborar o documento com as especificações;

## Referências
* [Repositório TWITTER](https://requisitos-de-software.github.io/2019.2-Twitter/modelagem/especificacao_suplementar/)
