### ISSUE TITLE
Modelagem - Use Case

### ISSUE THREAD

**Issue by nicaloribeiro** [Requisitos-de-Software/2020.1-Correios#8]
## Descrição 
* Descreve um conjunto de ações que um sistema ou um conjunto de sistemas deve desempenhar em colaboração com um ou mais usuários externos ao sistema;
* Especificações de casos de uso são narrativas em texto, descrevendo a unidade funcional, e são amplamente utilizados para representar requisitos funcionais nos sistemas.;
* Os diagramas de Casos de Uso são representações gráficas dos Casos de Uso e seus relacionamentos com outros casos de uso e atores;
* Neste diagrama um caso de uso é representado por uma elipse contendo, internamente, o nome do caso de uso e um ator é representado por um boneco palito;

## Tasks
- [x] Identificar os Casos de Uso com base nos requisitos levantados;
- [x] Elaborar as especificações de cada Caso de Uso;
- [x] Elaborar os diagramas de Caso de Uso;

## Referências
* [Caso de Uso - Wikipédia](https://pt.wikipedia.org/wiki/Caso_de_uso#:~:text=Uma%20das%20t%C3%A9cnicas%20mais%20populares,os%20requisitos%20de%20um%20sistema.)
* [Especificação de Caso de Uso - DevMedia](https://www.devmedia.com.br/artigo-engenharia-de-software-11-especificacao-de-casos-de-uso/12210#:~:text=apresentada%20e%20exemplificada.-,Especifica%C3%A7%C3%A3o%20de%20Casos%20de%20Uso,uma%20resposta%20para%20um%20ator.)
* [Diagramas de Caso de Uso - DevMedia](https://www.devmedia.com.br/o-que-e-uml-e-diagramas-de-caso-de-uso-introducao-pratica-a-uml/23408)
